name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      racket_version: '8.8'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - uses: Bogdanp/setup-racket@v1.9.1
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: ${{ env.racket_version }}
          sudo: never

      - name: Run test
        run: raco test tests
      - name: Run install
        run: raco pkg install
