name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      racket_version: '8.8'
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cache_path: |
              /opt/racket
          - os: windows-latest
            cache_path: |
              C:\Program Files\Racket
    steps:
      - uses: actions/checkout@v3

      - uses: Bogdanp/setup-racket@v1.9.1
        if: steps.restore.outputs.cache-hit != 'true'
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: ${{ env.racket_version }}
          sudo: never
          dest: '/opt/racket'

      - name: Cache Racket
        uses: actions/cache@v3
        with:
          path: ${{ matrix.cache_path }}
          key: ${{ matrix.os }}-racket-${{ env.racket_version }}

      - name: Run test
        run: raco test tests
      - name: Run install
        run: raco pkg install
